# This is a basic workflow to help you get started with Actions

name: dependencies

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]
    types: [ labeled ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: ${{ github.event.label.name == 'dependencies approval' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: cp -rf node_modules/vditor/dist/ src/main/resources/vditor/
      - uses: EndBug/add-and-commit@v7
        with:
          branch: ${{ github.head_ref }}
          message: 'publish vditor dist'
          add: "src/main/resources/vditor/"
          author_name: shuzijun
          author_email: shuzijun0109@gmail.com
